[package]
name = "find-torrent-data"
version = "0.1.1"
authors = ["Richard Patel <me@terorie.dev>"]
edition = "2018"
description = "Tool to search for and link files that are part of a torrent"

[dependencies]
clap = "2.33"
lava_torrent = "0.4"
multimap = "0.8"
sha-1 = "0.8"
walkdir = "2"
